In [102]:
import numpy as np

def get_world_map():
    world_map = np.zeros([10,10])
    
    #Goal
    world_map[7,9] = 3
    
    #Obstacle 1
    world_map[world_map.shape[0]-3:world_map.shape[0], 2:4] = 1
    world_map[world_map.shape[0]-4, 2:4] = 2
    world_map[world_map.shape[0]-4:world_map.shape[0], 1] = 2
    world_map[world_map.shape[0]-4:world_map.shape[0], 4] = 2
    
    #Obstacle 2
    world_map[1:3, 6:8] = 1
    world_map[0, 5:9] = 2
    world_map[3, 5:9] = 2
    world_map[0:4, 5] = 2
    world_map[0:4, 8] = 2
    
    #print(world_map)
    return world_map



def path_planner(ix, iy, heading, occGrid):
    gx = np.where(occGrid == 3)[1][0]
    gy = np.where(occGrid == 3)[0][0]
    #print(gy, gx)
    manhatten_grid = manhatten(gx, gy, 1, 1, occGrid)
    print("Occupancy Grid")
    print(occGrid)
    print("Manhatten Grid")
    print(manhatten_grid)
    path = []
    distance = manhatten_grid[iy, ix]
    path.append([iy, ix])
    #print(distance)
    distance, index = select_lowest(iy, ix, manhatten_grid)
    #print(distance)
    path.append(index)
    while(distance != 0):
        distance, index = select_lowest(index[0], index[1], manhatten_grid)
        #print(distance)
        path.append(index)
    print("Path Array:")
    print(path)
    path_matrix = np.zeros(manhatten_grid.shape)
    for node in path:
        #print(node)
        path_matrix[node[0], node[1]] = 1
    print("Path")
    print(path_matrix)
    
def select_lowest(row, col, manhatten_grid):
    minimum = 999
    min_index = [0,0]
    if(row != manhatten_grid.shape[0] - 1):
        minimum = manhatten_grid[row + 1, col]
        min_index = [row + 1, col]
    if(row != 0):
        if(minimum > manhatten_grid[row - 1, col]):
            minimum = manhatten_grid[row - 1, col]
            min_index = [row - 1, col]
    if(col != manhatten_grid.shape[1] - 1):
        if(minimum > manhatten_grid[row, col + 1]):
            minimum = manhatten_grid[row, col + 1]
            min_index = [row, col + 1]
    if(col != 0):
        if(minimum > manhatten_grid[row, col - 1]):
            minimum = manhatten_grid[row, col - 1]
            min_index = [row, col - 1]
            
    return minimum, min_index
    

def manhatten(x, y, distance, value, occGrid):
    manhatten_grid = np.zeros([occGrid.shape[0], occGrid.shape[1]])
    manhatten_grid[occGrid == 1] = 999
    manhatten_grid[occGrid == 2] = 999
#     print(occGrid.shape)
#     print(np.sum(manhatten_grid == 0))
    parse_next = 0
    while((np.sum(manhatten_grid == 0) != 1)):
        #print("Marking Distance: ", parse_next+1)
        if(parse_next == 0):
            manhatten_grid = mark_cells(y, x, parse_next, manhatten_grid, occGrid)
            parse_next += 1
            #print(manhatten_grid)
        next_indices = np.where(manhatten_grid == parse_next)
        for index in range(len(next_indices[0])):
            manhatten_grid = mark_cells(next_indices[0][index], next_indices[1][index], parse_next, manhatten_grid, occGrid)
        parse_next += 1
        #print(manhatten_grid)
    return manhatten_grid
    
        
def mark_cells(row, col, distance, manhatten_grid, occGrid):
    if(row != manhatten_grid.shape[0] - 1):
        if((manhatten_grid[row + 1, col] == 0) and (occGrid[row + 1, col] == 0)):
            manhatten_grid[row + 1, col] = distance + 1
    if(row != 0):
        if((manhatten_grid[row - 1, col] == 0) and (occGrid[row - 1, col] == 0)):
            manhatten_grid[row - 1, col] = distance + 1
    if(col != manhatten_grid.shape[1] - 1):
        if((manhatten_grid[row, col + 1] == 0) and (occGrid[row , col + 1] == 0)):
            manhatten_grid[row, col + 1] = distance + 1
    if(col != 0):
        if((manhatten_grid[row, col - 1] == 0) and (occGrid[row, col - 1] == 0)):
            manhatten_grid[row, col - 1] = distance + 1
    return manhatten_grid
occuGrid = get_world_map()
path_planner(0,9,0,occuGrid)

Occupancy Grid
[[ 0.  0.  0.  0.  0.  2.  2.  2.  2.  0.]
 [ 0.  0.  0.  0.  0.  2.  1.  1.  2.  0.]
 [ 0.  0.  0.  0.  0.  2.  1.  1.  2.  0.]
 [ 0.  0.  0.  0.  0.  2.  2.  2.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  2.  2.  2.  0.  0.  0.  0.  0.]
 [ 0.  2.  1.  1.  2.  0.  0.  0.  0.  3.]
 [ 0.  2.  1.  1.  2.  0.  0.  0.  0.  0.]
 [ 0.  2.  1.  1.  2.  0.  0.  0.  0.  0.]]
Manhatten Grid
[[  16.   15.   14.   13.   12.  999.  999.  999.  999.    7.]
 [  15.   14.   13.   12.   11.  999.  999.  999.  999.    6.]
 [  14.   13.   12.   11.   10.  999.  999.  999.  999.    5.]
 [  13.   12.   11.   10.    9.  999.  999.  999.  999.    4.]
 [  12.   11.   10.    9.    8.    7.    6.    5.    4.    3.]
 [  11.   10.    9.    8.    7.    6.    5.    4.    3.    2.]
 [  12.  999.  999.  999.  999.    5.    4.    3.    2.    1.]
 [  13.  999.  999.  999.  999.    4.    3.    2.    1.    0.]
 [  14.  999.  999.  999.  999.    

[[ 0.72824614  0.73032472]
 [ 0.52457013  0.36033719]]
0.360337189412
